export const REALTIME_TOPICS = {
  SEAT_UPDATED: 'seat.updated',
  RESERVATION_EXPIRED: 'reservation.expired',
  ORDER_PAID: 'order.paid',
  TICKET_ISSUED: 'ticket.issued',
  LIVE_PARTICIPANT_JOINED: 'livestream.participant.joined',
  LIVE_PARTICIPANT_LEFT: 'livestream.participant.left',
  LIVE_OVERLAY_UPDATED: 'live.overlay.updated',
  LIVE_MODERATION_ACTION: 'live.moderation.action',
  LIVE_ROOM_CREATED: 'live.room.created',
  LIVE_ROOM_UPDATED: 'live.room.updated',
  LIVE_COMMENT_CREATED: 'livestream.comment.created',
  LIVE_GIFT_SENT: 'livestream.gift.sent',
  LIVE_COMMENTING_TOGGLED: 'livestream.commenting.toggled',
  LIVE_VIEWER_COUNT_UPDATED: 'livestream.viewer_count.updated',
} as const;
